## This file is automatically generated by mklinktypelist.pl;
## Don't edit by hand.

$Whatpm::ContentChecker::LinkType = {
          'accessibility' => {
                               'effect' => [
                                             'hyperlink',
                                             'hyperlink'
                                           ],
                               'status' => 'proposal'
                             },
          'acquaintance' => {
                              'effect' => [
                                            'hyperlink',
                                            'hyperlink'
                                          ],
                              'status' => 'accepted'
                            },
          'ajax' => {
                      'effect' => [
                                    undef,
                                    'hyperlink'
                                  ],
                      'status' => 'proposal'
                    },
          'alternate' => {
                           'effect' => [
                                         'hyperlink',
                                         'hyperlink'
                                       ],
                           'status' => 'accepted'
                         },
          'answer' => {
                        'effect' => [
                                      'hyperlink',
                                      'hyperlink'
                                    ],
                        'status' => 'proposal'
                      },
          'appendix' => {
                          'effect' => [
                                        'hyperlink',
                                        'hyperlink'
                                      ],
                          'status' => 'synonym'
                        },
          'archive' => {
                         'effect' => [
                                       'hyperlink',
                                       'hyperlink'
                                     ],
                         'status' => 'synonym'
                       },
          'archives' => {
                          'effect' => [
                                        'hyperlink',
                                        'hyperlink'
                                      ],
                          'status' => 'accepted'
                        },
          'author' => {
                        'effect' => [
                                      'hyperlink',
                                      'hyperlink'
                                    ],
                        'status' => 'accepted'
                      },
          'begin' => {
                       'effect' => [
                                     'hyperlink',
                                     'hyperlink'
                                   ],
                       'status' => 'synonym'
                     },
          'bookmark' => {
                          'effect' => [
                                        undef,
                                        'hyperlink'
                                      ],
                          'status' => 'accepted'
                        },
          'canonical' => {
                           'effect' => [
                                         'hyperlink',
                                         undef
                                       ],
                           'status' => 'proposal'
                         },
          'canonical-domain' => {
                                  'effect' => [
                                                'external resource',
                                                undef
                                              ],
                                  'status' => 'proposal'
                                },
          'canonical-first' => {
                                 'effect' => [
                                               'external resource',
                                               'hyperlink'
                                             ],
                                 'status' => 'proposal'
                               },
          'canonical-human' => {
                                 'effect' => [
                                               'external resource',
                                               'hyperlink'
                                             ],
                                 'status' => 'proposal'
                               },
          'canonical-organization' => {
                                        'effect' => [
                                                      'external resource',
                                                      'hyperlink'
                                                    ],
                                        'status' => 'proposal'
                                      },
          'canonical-wwwnone' => {
                                   'effect' => [
                                                 'external resource',
                                                 'hyperlink'
                                               ],
                                   'status' => 'proposal'
                                 },
          'chapter' => {
                         'effect' => [
                                       'hyperlink',
                                       'hyperlink'
                                     ],
                         'status' => 'proposal'
                       },
          'child' => {
                       'effect' => [
                                     'hyperlink',
                                     'hyperlink'
                                   ],
                       'status' => 'accepted'
                     },
          'co-resident' => {
                             'effect' => [
                                           'hyperlink',
                                           'hyperlink'
                                         ],
                             'status' => 'accepted'
                           },
          'co-worker' => {
                           'effect' => [
                                         'hyperlink',
                                         'hyperlink'
                                       ],
                           'status' => 'accepted'
                         },
          'colleague' => {
                           'effect' => [
                                         'hyperlink',
                                         'hyperlink'
                                       ],
                           'status' => 'accepted'
                         },
          'comment' => {
                         'effect' => [
                                       'hyperlink',
                                       'hyperlink'
                                     ],
                         'status' => 'synonym'
                       },
          'contact' => {
                         'effect' => [
                                       'hyperlink',
                                       'hyperlink'
                                     ],
                         'status' => 'accepted'
                       },
          'content-negotiation' => {
                                     'effect' => [
                                                   'external resource',
                                                   undef
                                                 ],
                                     'status' => 'synonym'
                                   },
          'contents' => {
                          'effect' => [
                                        'hyperlink',
                                        'hyperlink'
                                      ],
                          'status' => 'synonym'
                        },
          'contributor' => {
                             'effect' => [
                                           'hyperlink',
                                           'hyperlink'
                                         ],
                             'status' => 'proposal'
                           },
          'copyright' => {
                           'effect' => [
                                         'hyperlink',
                                         'hyperlink'
                                       ],
                           'status' => 'synonym'
                         },
          'crush' => {
                       'effect' => [
                                     'hyperlink',
                                     'hyperlink'
                                   ],
                       'status' => 'accepted'
                     },
          'date' => {
                      'effect' => [
                                    'hyperlink',
                                    'hyperlink'
                                  ],
                      'status' => 'accepted'
                    },
          'details' => {
                         'effect' => [
                                       'hyperlink',
                                       'hyperlink'
                                     ],
                         'status' => 'proposal'
                       },
          'dns-prefetch' => {
                              'effect' => [
                                            'external resource',
                                            undef
                                          ],
                              'status' => 'proposal'
                            },
          'edit' => {
                      'effect' => [
                                    'hyperlink',
                                    'hyperlink'
                                  ],
                      'status' => 'proposal'
                    },
          'edituri' => {
                         'effect' => [
                                       'hyperlink',
                                       undef
                                     ],
                         'status' => 'proposal'
                       },
          'enclosure' => {
                           'effect' => [
                                         'hyperlink',
                                         'hyperlink'
                                       ],
                           'status' => 'proposal'
                         },
          'end' => {
                     'effect' => [
                                   'hyperlink',
                                   'hyperlink'
                                 ],
                     'status' => 'synonym'
                   },
          'enlarged' => {
                          'effect' => [
                                        undef,
                                        'hyperlink'
                                      ],
                          'status' => 'proposal'
                        },
          'extension' => {
                           'effect' => [
                                         'hyperlink',
                                         'hyperlink'
                                       ],
                           'status' => 'proposal'
                         },
          'external' => {
                          'effect' => [
                                        undef,
                                        'hyperlink'
                                      ],
                          'status' => 'accepted'
                        },
          'first' => {
                       'effect' => [
                                     'hyperlink',
                                     'hyperlink'
                                   ],
                       'status' => 'accepted'
                     },
          'friend' => {
                        'effect' => [
                                      'hyperlink',
                                      'hyperlink'
                                    ],
                        'status' => 'accepted'
                      },
          'gallery' => {
                         'effect' => [
                                       'hyperlink',
                                       'hyperlink'
                                     ],
                         'status' => 'proposal'
                       },
          'glossary' => {
                          'effect' => [
                                        'hyperlink',
                                        'hyperlink'
                                      ],
                          'status' => 'proposal'
                        },
          'help' => {
                      'effect' => [
                                    'hyperlink',
                                    'hyperlink'
                                  ],
                      'status' => 'accepted'
                    },
          'hub' => {
                     'effect' => [
                                   'hyperlink',
                                   undef
                                 ],
                     'status' => 'proposal'
                   },
          'i18nrules' => {
                           'effect' => [
                                         'hyperlink',
                                         undef
                                       ],
                           'status' => 'proposal'
                         },
          'icon' => {
                      'effect' => [
                                    'external resource',
                                    undef
                                  ],
                      'status' => 'accepted'
                    },
          'index' => {
                       'effect' => [
                                     'hyperlink',
                                     'hyperlink'
                                   ],
                       'status' => 'accepted'
                     },
          'jump' => {
                      'effect' => [
                                    undef,
                                    'hyperlink'
                                  ],
                      'status' => 'proposal'
                    },
          'kin' => {
                     'effect' => [
                                   'hyperlink',
                                   'hyperlink'
                                 ],
                     'status' => 'accepted'
                   },
          'last' => {
                      'effect' => [
                                    'hyperlink',
                                    'hyperlink'
                                  ],
                      'status' => 'accepted'
                    },
          'latest-version' => {
                                'effect' => [
                                              'hyperlink',
                                              'hyperlink'
                                            ],
                                'status' => 'proposal'
                              },
          'license' => {
                         'effect' => [
                                       'hyperlink',
                                       'hyperlink'
                                     ],
                         'status' => 'accepted'
                       },
          'logout' => {
                        'effect' => [
                                      'external resource',
                                      undef
                                    ],
                        'status' => 'proposal'
                      },
          'longdesc' => {
                          'effect' => [
                                        'hyperlink',
                                        'hyperlink'
                                      ],
                          'status' => 'proposal'
                        },
          'maintainer' => {
                            'effect' => [
                                          'hyperlink',
                                          'hyperlink'
                                        ],
                            'status' => 'synonym'
                          },
          'map' => {
                     'effect' => [
                                   'hyperlink',
                                   'hyperlink'
                                 ],
                     'status' => 'proposal'
                   },
          'me' => {
                    'effect' => [
                                  'hyperlink',
                                  'hyperlink'
                                ],
                    'status' => 'accepted'
                  },
          'met' => {
                     'effect' => [
                                   'hyperlink',
                                   'hyperlink'
                                 ],
                     'status' => 'accepted'
                   },
          'meta' => {
                      'effect' => [
                                    'external resource',
                                    'hyperlink'
                                  ],
                      'status' => 'proposal'
                    },
          'muse' => {
                      'effect' => [
                                    'hyperlink',
                                    'hyperlink'
                                  ],
                      'status' => 'accepted'
                    },
          'neighbor' => {
                          'effect' => [
                                        'hyperlink',
                                        'hyperlink'
                                      ],
                          'status' => 'accepted'
                        },
          'next' => {
                      'effect' => [
                                    'hyperlink',
                                    'hyperlink'
                                  ],
                      'status' => 'accepted'
                    },
          'next-archive' => {
                              'effect' => [
                                            'hyperlink',
                                            'hyperlink'
                                          ],
                              'status' => 'proposal'
                            },
          'nofollow' => {
                          'effect' => [
                                        undef,
                                        'annotation'
                                      ],
                          'status' => 'accepted'
                        },
          'noprefetch' => {
                            'effect' => [
                                          'external resource',
                                          'hyperlink'
                                        ],
                            'status' => 'proposal'
                          },
          'noreferrer' => {
                            'effect' => [
                                          undef,
                                          'annotation'
                                        ],
                            'status' => 'accepted'
                          },
          'note' => {
                      'effect' => [
                                    undef,
                                    'hyperlink'
                                  ],
                      'status' => 'proposal'
                    },
          'openid.delegate' => {
                                 'effect' => [
                                               'external resource',
                                               undef
                                             ],
                                 'status' => 'proposal'
                               },
          'openid.server' => {
                               'effect' => [
                                             'external resource',
                                             undef
                                           ],
                               'status' => 'proposal'
                             },
          'openid2.local_id' => {
                                  'effect' => [
                                                'external resource',
                                                undef
                                              ],
                                  'status' => 'proposal'
                                },
          'openid2.provider' => {
                                  'effect' => [
                                                'external resource',
                                                undef
                                              ],
                                  'status' => 'proposal'
                                },
          'parent' => {
                        'effect' => [
                                      'hyperlink',
                                      'hyperlink'
                                    ],
                        'status' => 'accepted'
                      },
          'payment' => {
                         'effect' => [
                                       'hyperlink',
                                       'hyperlink'
                                     ],
                         'status' => 'proposal'
                       },
          'pgpkey' => {
                        'effect' => [
                                      'hyperlink',
                                      undef
                                    ],
                        'status' => 'proposal'
                      },
          'pingback' => {
                          'effect' => [
                                        'external resource',
                                        undef
                                      ],
                          'status' => 'accepted',
                          'unique' => 1
                        },
          'posting' => {
                         'effect' => [
                                       'hyperlink',
                                       'hyperlink'
                                     ],
                         'status' => 'synonym'
                       },
          'prefetch' => {
                          'effect' => [
                                        'external resource',
                                        undef
                                      ],
                          'status' => 'accepted'
                        },
          'presentation' => {
                              'effect' => [
                                            'external resource',
                                            'hyperlink'
                                          ],
                              'status' => 'proposal'
                            },
          'prev' => {
                      'effect' => [
                                    'hyperlink',
                                    'hyperlink'
                                  ],
                      'status' => 'accepted'
                    },
          'prev-archive' => {
                              'effect' => [
                                            'hyperlink',
                                            'hyperlink'
                                          ],
                              'status' => 'proposal'
                            },
          'previous' => {
                          'effect' => [
                                        'hyperlink',
                                        'hyperlink'
                                      ],
                          'status' => 'synonym'
                        },
          'print' => {
                       'effect' => [
                                     'external resource',
                                     'hyperlink'
                                   ],
                       'status' => 'proposal'
                     },
          'problem' => {
                         'effect' => [
                                       'hyperlink',
                                       'hyperlink'
                                     ],
                         'status' => 'synonym'
                       },
          'profile' => {
                         'effect' => [
                                       'hyperlink',
                                       'hyperlink'
                                     ],
                         'status' => 'proposal'
                       },
          'question' => {
                          'effect' => [
                                        'hyperlink',
                                        'hyperlink'
                                      ],
                          'status' => 'proposal'
                        },
          'related' => {
                         'effect' => [
                                       'hyperlink',
                                       'hyperlink'
                                     ],
                         'status' => 'proposal'
                       },
          'reply' => {
                       'effect' => [
                                     'hyperlink',
                                     'hyperlink'
                                   ],
                       'status' => 'proposal'
                     },
          'resource-description' => {
                                      'effect' => [
                                                    'external resource',
                                                    undef
                                                  ],
                                      'status' => 'synonym'
                                    },
          'resource-package' => {
                                  'effect' => [
                                                'external resource',
                                                undef
                                              ],
                                  'status' => 'proposal'
                                },
          'resources' => {
                           'effect' => [
                                         'external resource',
                                         undef
                                       ],
                           'status' => 'proposal'
                         },
          'reviewer' => {
                          'effect' => [
                                        'hyperlink',
                                        undef
                                      ],
                          'status' => 'proposal'
                        },
          'script' => {
                        'effect' => [
                                      undef,
                                      undef
                                    ],
                        'status' => 'rejected'
                      },
          'search' => {
                        'effect' => [
                                      'hyperlink',
                                      'hyperlink'
                                    ],
                        'status' => 'accepted'
                      },
          'section' => {
                         'effect' => [
                                       'hyperlink',
                                       'hyperlink'
                                     ],
                         'status' => 'synonym'
                       },
          'self' => {
                      'effect' => [
                                    'hyperlink',
                                    'hyperlink'
                                  ],
                      'status' => 'proposal'
                    },
          'service' => {
                         'effect' => [
                                       'external resource',
                                       undef
                                     ],
                         'status' => 'proposal'
                       },
          'shortlink' => {
                           'effect' => [
                                         'hyperlink',
                                         'hyperlink'
                                       ],
                           'status' => 'proposal'
                         },
          'sibling' => {
                         'effect' => [
                                       'hyperlink',
                                       'hyperlink'
                                     ],
                         'status' => 'accepted'
                       },
          'sidebar' => {
                         'effect' => [
                                       'hyperlink',
                                       'hyperlink'
                                     ],
                         'status' => 'accepted'
                       },
          'slides' => {
                        'effect' => [
                                      'external resource',
                                      'hyperlink'
                                    ],
                        'status' => 'synonym'
                      },
          'slideshow' => {
                           'effect' => [
                                         'external resource',
                                         'hyperlink'
                                       ],
                           'status' => 'synonym'
                         },
          'spouse' => {
                        'effect' => [
                                      'hyperlink',
                                      'hyperlink'
                                    ],
                        'status' => 'accepted'
                      },
          'start' => {
                       'effect' => [
                                     'hyperlink',
                                     'hyperlink'
                                   ],
                       'status' => 'synonym'
                     },
          'statechart' => {
                            'effect' => [
                                          'external resource',
                                          undef
                                        ],
                            'status' => 'proposal'
                          },
          'stylesheet' => {
                            'effect' => [
                                          'external resource',
                                          undef
                                        ],
                            'status' => 'accepted'
                          },
          'subject' => {
                         'effect' => [
                                       'hyperlink',
                                       'hyperlink'
                                     ],
                         'status' => 'synonym'
                       },
          'subsection' => {
                            'effect' => [
                                          'hyperlink',
                                          'hyperlink'
                                        ],
                            'status' => 'synonym'
                          },
          'sweetheart' => {
                            'effect' => [
                                          'hyperlink',
                                          'hyperlink'
                                        ],
                            'status' => 'accepted'
                          },
          'tag' => {
                     'effect' => [
                                   'hyperlink',
                                   'hyperlink'
                                 ],
                     'status' => 'accepted'
                   },
          'technicalauthor' => {
                                 'effect' => [
                                               'hyperlink',
                                               'hyperlink'
                                             ],
                                 'status' => 'proposal'
                               },
          'thread' => {
                        'effect' => [
                                      'hyperlink',
                                      'hyperlink'
                                    ],
                        'status' => 'proposal'
                      },
          'timesheet' => {
                           'effect' => [
                                         'external resource',
                                         undef
                                       ],
                           'status' => 'proposal'
                         },
          'toc' => {
                     'effect' => [
                                   'hyperlink',
                                   'hyperlink'
                                 ],
                     'status' => 'synonym'
                   },
          'top' => {
                     'effect' => [
                                   'hyperlink',
                                   'hyperlink'
                                 ],
                     'status' => 'synonym'
                   },
          'topic' => {
                       'effect' => [
                                     'hyperlink',
                                     'hyperlink'
                                   ],
                       'status' => 'synonym'
                     },
          'translatedfrom' => {
                                'effect' => [
                                              'hyperlink',
                                              'hyperlink'
                                            ],
                                'status' => 'proposal'
                              },
          'translator' => {
                            'effect' => [
                                          'hyperlink',
                                          'hyperlink'
                                        ],
                            'status' => 'proposal'
                          },
          'up' => {
                    'effect' => [
                                  'hyperlink',
                                  'hyperlink'
                                ],
                    'status' => 'accepted'
                  },
          'us' => {
                    'effect' => [
                                  'hyperlink',
                                  'hyperlink'
                                ],
                    'status' => 'proposal'
                  },
          'webmaster' => {
                           'effect' => [
                                         'hyperlink',
                                         'hyperlink'
                                       ],
                           'status' => 'proposal'
                         },
          'widget' => {
                        'effect' => [
                                      'hyperlink',
                                      'hyperlink'
                                    ],
                        'status' => 'proposal'
                      },
          'wlwmanifest' => {
                             'effect' => [
                                           'hyperlink',
                                           undef
                                         ],
                             'status' => 'proposal'
                           }
        };
1;
__DATA__

=head1 NAME

mklinktypelist.pl - The link type list generator for the Whatpm conformance checker

_LinkTypeList.pm - The link type list for the Whatpm conformance checker

=head1 SYNOPSIS

Generation:

  $ make update-_LinkTypeList.pm _LinkTypeList.pm

=head1 DESCRIPTION

The C<_LinkTypeList.pm> Perl module file contains a list of link types
that might be used formally in HTML C<rel> attributes, conforming or
non-conforming, according to the Web Applications 1.0 specification.
This Perl module is referenced from the Whatpm DOM conformance
checker, i.e. L<Whatpm::ContentChecker>.

The C<mklinktypelist.pl> script is the script that is used to generate
the C<_LinkTypeList.pm> from the list of available link C<rel>
extensions in the WHATWG Wiki.  The script can be invoked by using the
C<make> command as mentioned in the L</"SYNOPSIS"> section.

=head1 WILLFUL VIOLATIONS

As the WHATWG Wiki is freely editable by any interested party, it
might sometimes include broken or incorrect data that are
inappropriate for the conformance checker implementation.  Rather than
complying with the spec literally, we choose to willfully violate such
broken data from the wiki page.  Specifically,

=over 4

=item Table rows whose "Keyword" cell contains "[" or "]" are ignored.

=item Keywords in the "Synonyms" cell that contain "(", ")", "<", or ">" are ignored.

=back

=head1 SEE ALSO

C<Makefile>.

L<Whatpm::ContentChecker>.

Web Applications 1.0 - Link types
<http://www.whatwg.org/specs/web-apps/current-work/complete.html#linkTypes>.

RelExtensions - WHATWG Wiki
<http://wiki.whatwg.org/wiki/RelExtensions>.

=head1 AUTHORS

The author of C<mklinktypelist.pl> is Wakaba <w@suika.fam.cx>.

Authors of the "RelExtensions" page in the WHATWG Wiki, from which the
C<_LinkTypeList.pm> Perl module is generated, are WHATWG contributors.
For the revision history of the wiki pgae, see
<http://wiki.whatwg.org/index.php?title=RelExtensions&action=history>.

=head1 LICENSE

Copyright (C) 2006 The WHATWG Contributors

Copyright 2007-2010 Wakaba <w@suika.fam.cx>.

Permission is hereby granted, free of charge, to any person obtaining a 
copy of this software and associated documentation files (the "Software"), 
to deal in the Software without restriction, including without limitation 
the rights to use, copy, modify, merge, publish, distribute, sublicense, 
and/or sell copies of the Software, and to permit persons to whom the 
Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included 
in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS 
OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE 
SOFTWARE. 

(So-called "MIT license".  Source: "WHATWG Wiki:Copyrights"
<http://wiki.whatwg.org/wiki/WHATWG_Wiki:Copyrights>)

=cut

