=head1 NAME

Whatpm::Errors - Error handling in Whatpm modules

=head1 DESCRIPTION

This is a placeholder for the documentation on error handlings in
Whatpm modules.

=head1 SEE ALSO

WebHACC - Description of Errors
<http://suika.fam.cx/gate/2007/html/error-description>.

SuikaWiki:Whatpm Error Types (outdated)
<http://suika.fam.cx/~wakaba/wiki/sw/n/Whatpm%20Error%20Types>.

=head1 LICENSE

Copyright 2012 Wakaba <w@suika.fam.cx>.

This program is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

