=head1 NAME

Whatpm::Errors - Error handling in Whatpm modules

=head1 DESCRIPTION

This is a placeholder for the documentation on error handlings in
Whatpm modules.

=head1 SEE ALSO

WebHACC - Description of Errors
<https://suika.suikawiki.org/gate/2007/html/error-description>.

SuikaWiki:Whatpm Error Types (outdated)
<https://suika.suikawiki.org/~wakaba/wiki/sw/n/Whatpm%20Error%20Types>.

=head1 LICENSE

Copyright 2012 Wakaba <wakaba@suikawiki.org>.

This program is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

