=head1 NAME

Whatpm::HTML - Old HTML parser API

=head1 DESCRIPTION

The C<Whatpm::HTML> module provides an out-of-date API to HTML parser
for backward compatibility.  Use L<Whatpm::HTML::Parser> and
L<Whatpm::HTML::Serializer> for new applications.

=head1 SEE ALSO

L<Whatpm::HTML::Parser>, L<Whatpm::HTML::Serializer>.

=head1 AUTHOR

Wakaba <w@suika.fam.cx>.

=head1 LICENSE

Copyright 2007-2012 Wakaba <w@suika.fam.cx>.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
