=head1 NAME

Whatpm::CSS::Parser - A CSS Parser

=head1 SYNOPSIS

TBD

=head1 METHODS

TBD

=head1 SUPPORTED STANDARDS

This module implements CSS, Selectors, Media Querties, and CSSOM.  See
<https://suika.suikawiki.org/gate/2007/html/standards#css> for more
information.

=head1 SEE ALSO

CSS Namespace <http://www.w3.org/TR/css3-namespace/>.

=head1 AUTHOR

Wakaba <wakaba@suikawiki.org>.

=head1 LICENSE

Copyright 2007-2011 Wakaba <wakaba@suikawiki.org>.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
