=head1 NAME

Whatpm::ContentChecker::HTML - DOM Conformance Checker - HTML

=head1 DESCRIPTION

The C<Whatpm::ContentChecker::HTML> implements conformance checking of
HTML vocabulary, i.e. elements and attributes in the HTML namespace as
well as attributes in no namespace of HTML elements.

For more information, see L<Whatpm::ContentChecker>.

=head1 SEE ALSO

Web Applications 1.0
<http://www.whatwg.org/specs/web-apps/current-work/complete.html> -
the HTML standard, including HTML5.

manakai's Conformance Checking Guideline for Obsolete HTML Elements
and Attributes
<http://suika.fam.cx/www/markup/html/exts/manakai-obsvocab> -
Requirements for non-standard elements and attributes.

L<Whatpm::ContentChecker>.

=head1 AUTHOR

Wakaba <w@suika.fam.cx>

=head1 LICENSE

Copyright 2007-2010 Wakaba <w@suika.fam.cx>.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
