#!/usr/bin/perl 
## This file is automatically generated
## 	at 2005-09-28T03:55:07+00:00,
## 	from file "lib/Message/DOM/DOMLS.dis",
## 	module <http://suika.fam.cx/~wakaba/archive/2004/8/18/manakai-dom#ManakaiDOM.DOMLS>,
## 	for <http://suika.fam.cx/~wakaba/archive/2004/8/18/manakai-dom#ManakaiDOMLatest>.
## Don't edit by hand!
use strict;
require Message::Util::Error::DOMException;
require Message::DOM::DOMCore;
require Message::Util::Error;
require Message::DOM::DOMMain;
package Message::DOM::DOMLS;
our $VERSION = 20050928.0355;
sub SERIALIZE_ERR ();
sub MODE_SYNCHRONOUS ();
sub MODE_ASYNCHRONOUS ();
sub PARSE_ERR ();
sub AUTOLOAD {

#line 1 "lib/Message/DOM/DOMLS.dis [u] (Chunk #1)"

        my $al = our $AUTOLOAD;
        $al =~ s/.+:://;
        if ({'SERIALIZE_ERR', 'Message::DOM::DOMLS::SERIALIZE_ERR', 'MODE_SYNCHRONOUS', 'Message::DOM::DOMLS::MODE_SYNCHRONOUS', 'MODE_ASYNCHRONOUS', 'Message::DOM::DOMLS::MODE_ASYNCHRONOUS', 'PARSE_ERR', 'Message::DOM::DOMLS::PARSE_ERR'}->{$al}) {
          no strict 'refs';
          *{$AUTOLOAD} = \&{{'SERIALIZE_ERR', 'Message::DOM::DOMLS::SERIALIZE_ERR', 'MODE_SYNCHRONOUS', 'Message::DOM::DOMLS::MODE_SYNCHRONOUS', 'MODE_ASYNCHRONOUS', 'Message::DOM::DOMLS::MODE_ASYNCHRONOUS', 'PARSE_ERR', 'Message::DOM::DOMLS::PARSE_ERR'}->{$al}};
          goto &{$AUTOLOAD};
        } else {
          require Carp;
          Carp::croak (qq<Can't locate method "$AUTOLOAD">);
        }
      
#line 1 "lib/Message/DOM/DOMLS.dis [/u] (Chunk #2)"
}
sub import {

#line 1 "lib/Message/DOM/DOMLS.dis [u] (Chunk #3)"

        my $self = shift;
        if (@_) {
          local $Exporter::ExportLevel = $Exporter::ExportLevel + 1;
          $self->SUPER::import (@_);
          for (grep {not /\W/} @_) {
            eval qq{$_};
          }
        }
      
#line 1 "lib/Message/DOM/DOMLS.dis [/u] (Chunk #4)"
}
our %EXPORT_TAG = ('LSExceptionCode', ['PARSE_ERR', 'SERIALIZE_ERR'], 'DOMImplementationLSMode', ['MODE_ASYNCHRONOUS', 'MODE_SYNCHRONOUS']);
our @EXPORT_OK = ('PARSE_ERR', 'SERIALIZE_ERR', 'MODE_ASYNCHRONOUS', 'MODE_SYNCHRONOUS');
use Exporter; push our @ISA, 'Exporter';
package Message::DOM::IFLatest::LSException;
our $VERSION = 20050928.0355;
push our @ISA, 'Message::Util::Error';
package Message::DOM::DOMLS::ManakaiDOMLSException;
our $VERSION = 20050928.0355;
push our @ISA, 'Message::Util::Error::DOMException::ManakaiDOMException', 'Message::DOM::DOMMain::ManakaiDOMObject', 'Message::DOM::IF::LSException', 'Message::DOM::IFLatest::LSException', 'Message::DOM::IFLevel3::LSException', 'Message::Util::IF::ManakaiDOMExceptionIF';
sub PARSE_ERR () {
81}
sub ___error_def () {

#line 1 "lib/Message/DOM/DOMLS.dis [u] (Chunk #5)"
{'PARSE_ERR', {'http://suika.fam.cx/~wakaba/archive/2004/8/18/dom-core#code', '81', 'http://suika.fam.cx/~wakaba/archive/2004/8/4/manakai-dom-exception#subtype', {}, 'description', 'An attempt was made to load a document or an XML fragment using <IF::LSParser> and the processing has been stopped.'}, 'SERIALIZE_ERR', {'http://suika.fam.cx/~wakaba/archive/2004/8/18/dom-core#code', '82', 'http://suika.fam.cx/~wakaba/archive/2004/8/4/manakai-dom-exception#subtype', {}, 'description', 'An attempt was made to serialize a <IF::DOMCore:Node> using <IF::LSSerializer> and the processing has been stop.'}}
#line 1 "lib/Message/DOM/DOMLS.dis [/u] (Chunk #6)"
}
sub SERIALIZE_ERR () {
82}
$Message::DOM::ClassFeature{q<Message::DOM::DOMLS::ManakaiDOMLSException>} = {'ls-async', {'', '1', '3.0', '1'}, 'ls', {'', '1', '3.0', '1'}};
$Message::DOM::ClassPoint{q<Message::DOM::DOMLS::ManakaiDOMLSException>} = 6;
package Message::DOM::DOMLS::ManakaiDOMImplementationLS;
our $VERSION = 20050928.0355;
push our @ISA, 'Message::DOM::DOMCore::ManakaiDOMImplementation', 'Message::DOM::IF::DOMImplementationLS', 'Message::DOM::IFLatest::DOMImplementationLS', 'Message::DOM::IFLevel3::DOMImplementationLS';
sub MODE_ASYNCHRONOUS () {
2}
sub create_ls_output ($) {
my ($self) = @_;
my $r;

{
#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=DOMImplementationLS][@QName=ManakaiDOMImplementationLS][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Method[@Name=createLSOutput][@type=DISLang|Method]/Return[@Type=LSOutput][@type=DISLang|MethodReturn]/PerlDef [b] (Chunk #13)"

#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=DOMImplementationLS][@QName=ManakaiDOMImplementationLS][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Method[@Name=createLSOutput][@type=DISLang|Method]/Return[@Type=LSOutput][@type=DISLang|MethodReturn]/PerlDef [bc] (Chunk #11)"

#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=DOMImplementationLS][@QName=ManakaiDOMImplementationLS][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Method[@Name=createLSOutput][@type=DISLang|Method]/Return[@Type=LSOutput][@type=DISLang|MethodReturn]/PerlDef [u] (Chunk #7)"
$r = 
#line 1 "lib/Message/DOM/DOMLS.dis [/u] (Chunk #8)"
Message::DOM::DOMLS::ManakaiDOMLSOutput->_new
#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=DOMImplementationLS][@QName=ManakaiDOMImplementationLS][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Method[@Name=createLSOutput][@type=DISLang|Method]/Return[@Type=LSOutput][@type=DISLang|MethodReturn]/PerlDef [u] (Chunk #9)"
;
#line 1 "lib/Message/DOM/DOMLS.dis [/u] (Chunk #10)"

#line 1 "lib/Message/DOM/DOMLS.dis [/bc] (Chunk #12)"

#line 1 "lib/Message/DOM/DOMLS.dis [/b] (Chunk #14)"
}
$r}
sub create_ls_serializer ($) {
my ($self) = @_;
my $r;
report Message::Util::Error::DOMException::CoreException -object => $self, '-type' => 'NOT_SUPPORTED_ERR', 'http://suika.fam.cx/~wakaba/archive/2004/8/4/manakai-dom-exception#method' => 'create_ls_serializer', 'http://suika.fam.cx/~wakaba/archive/2004/8/4/manakai-dom-exception#subtype' => 'http://suika.fam.cx/~wakaba/archive/2004/8/4/manakai-dom-exception#MDOM_IMPL_METHOD_NOT_IMPLEMENTED', 'http://suika.fam.cx/~wakaba/archive/2004/8/4/manakai-dom-exception#class' => 'Message::DOM::DOMLS::ManakaiDOMImplementationLS';
$r}
sub create_ls_parser ($$;$) {
my ($self, $mode, $schemaType) = @_;
my $r;
report Message::Util::Error::DOMException::CoreException -object => $self, '-type' => 'NOT_SUPPORTED_ERR', 'http://suika.fam.cx/~wakaba/archive/2004/8/4/manakai-dom-exception#method' => 'create_ls_parser', 'http://suika.fam.cx/~wakaba/archive/2004/8/4/manakai-dom-exception#subtype' => 'http://suika.fam.cx/~wakaba/archive/2004/8/4/manakai-dom-exception#MDOM_IMPL_METHOD_NOT_IMPLEMENTED', 'http://suika.fam.cx/~wakaba/archive/2004/8/4/manakai-dom-exception#class' => 'Message::DOM::DOMLS::ManakaiDOMImplementationLS';
$r}
sub MODE_SYNCHRONOUS () {
1}
sub create_ls_input ($) {
my ($self) = @_;
my $r;

{
#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=DOMImplementationLS][@QName=ManakaiDOMImplementationLS][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Method[@Name=createLSInput][@type=DISLang|Method]/Return[@Type=LSInput][@type=DISLang|MethodReturn]/PerlDef [b] (Chunk #21)"

#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=DOMImplementationLS][@QName=ManakaiDOMImplementationLS][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Method[@Name=createLSInput][@type=DISLang|Method]/Return[@Type=LSInput][@type=DISLang|MethodReturn]/PerlDef [bc] (Chunk #19)"

#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=DOMImplementationLS][@QName=ManakaiDOMImplementationLS][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Method[@Name=createLSInput][@type=DISLang|Method]/Return[@Type=LSInput][@type=DISLang|MethodReturn]/PerlDef [u] (Chunk #15)"
$r = 
#line 1 "lib/Message/DOM/DOMLS.dis [/u] (Chunk #16)"
Message::DOM::DOMLS::ManakaiDOMLSInput->_new
#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=DOMImplementationLS][@QName=ManakaiDOMImplementationLS][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Method[@Name=createLSInput][@type=DISLang|Method]/Return[@Type=LSInput][@type=DISLang|MethodReturn]/PerlDef [u] (Chunk #17)"
;
#line 1 "lib/Message/DOM/DOMLS.dis [/u] (Chunk #18)"

#line 1 "lib/Message/DOM/DOMLS.dis [/bc] (Chunk #20)"

#line 1 "lib/Message/DOM/DOMLS.dis [/b] (Chunk #22)"
}
$r}
$Message::DOM::ImplFeature{q<Message::DOM::DOMLS::ManakaiDOMImplementationLS>}->{q<ls>}->{q<3.0>} ||= 1;
$Message::DOM::ImplFeature{q<Message::DOM::DOMLS::ManakaiDOMImplementationLS>}->{q<ls>}->{q<>} = 1;
$Message::DOM::ClassFeature{q<Message::DOM::DOMLS::ManakaiDOMImplementationLS>} = {'core', {'2.0', '1', '', '1', '3.0', '1', '1.0', '1'}, 'xmlversion', {'', '1', '1.1', '1', '1.0', '1'}, 'ls-async', {'', '1', '3.0', '1'}, 'xml', {'2.0', '1', '', '1', '3.0', '1', '1.0', '1'}, 'ls', {'', '1', '3.0', '1'}, 'http://suika.fam.cx/~wakaba/archive/2004/8/18/manakai-dom#minimum', {'', '1', '3.0', '1'}};
$Message::DOM::ClassPoint{q<Message::DOM::DOMLS::ManakaiDOMImplementationLS>} = 23.1;
$Message::DOM::ManakaiDOMImplementationSource::SourceClass{q<Message::DOM::DOMLS::ManakaiDOMImplementationLS>} = 1;
$Message::DOM::ManakaiDOMImplementation::CompatClass{q<Message::DOM::DOMLS::ManakaiDOMImplementationLS>} = 1;
$Message::DOM::ManakaiDOMImplementationSource::SourceClass{q<Message::DOM::DOMLS::ManakaiDOMImplementationLS>} = 1;
$Message::DOM::ManakaiDOMImplementation::CompatClass{q<Message::DOM::DOMLS::ManakaiDOMImplementationLS>} = 1;
$Message::Util::ManakaiNode::ManakaiNodeRef::Prop{q<Message::DOM::DOMLS::ManakaiDOMImplementationLS>} = {};
package Message::DOM::DOMLS::ManakaiDOMLSInput;
our $VERSION = 20050928.0355;
push our @ISA, 'Message::DOM::DOMMain::ManakaiDOMObject', 'Message::DOM::IF::LSInput', 'Message::DOM::IFLatest::LSInput', 'Message::DOM::IFLevel3::LSInput';
sub public_id ($;$) {
if (@_ == 1) {
#line 1 "lib/Message/DOM/DOMLS.dis [bc] (Chunk #29)"
my ($self) = @_;
my $r;

{
#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSInput][@QName=ManakaiDOMLSInput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=publicId][@Type=DOMMain:DOMString][@type=DISLang|Attribute]/Get[@type=DISLang|AttributeGet]/PerlDef [b] (Chunk #27)"

#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSInput][@QName=ManakaiDOMLSInput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=publicId][@Type=DOMMain:DOMString][@type=DISLang|Attribute]/Get[@type=DISLang|AttributeGet]/PerlDef [bc] (Chunk #25)"

#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSInput][@QName=ManakaiDOMLSInput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=publicId][@Type=DOMMain:DOMString][@type=DISLang|Attribute]/Get[@type=DISLang|AttributeGet]/PerlDef [u] (Chunk #23)"
$r = $self->{public_id};
#line 1 "lib/Message/DOM/DOMLS.dis [/u] (Chunk #24)"

#line 1 "lib/Message/DOM/DOMLS.dis [/bc] (Chunk #26)"

#line 1 "lib/Message/DOM/DOMLS.dis [/b] (Chunk #28)"
}
$r;

#line 1 "lib/Message/DOM/DOMLS.dis [/bc] (Chunk #30)"
} else {
#line 1 "lib/Message/DOM/DOMLS.dis [bc] (Chunk #37)"
my ($self, $given) = @_;

{
#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSInput][@QName=ManakaiDOMLSInput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=publicId][@Type=DOMMain:DOMString][@type=DISLang|Attribute]/Set[@type=DISLang|AttributeSet]/PerlDef [b] (Chunk #35)"

#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSInput][@QName=ManakaiDOMLSInput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=publicId][@Type=DOMMain:DOMString][@type=DISLang|Attribute]/Set[@type=DISLang|AttributeSet]/PerlDef [bc] (Chunk #33)"

#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSInput][@QName=ManakaiDOMLSInput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=publicId][@Type=DOMMain:DOMString][@type=DISLang|Attribute]/Set[@type=DISLang|AttributeSet]/PerlDef [u] (Chunk #31)"
$self->{public_id} = $self;
#line 1 "lib/Message/DOM/DOMLS.dis [/u] (Chunk #32)"

#line 1 "lib/Message/DOM/DOMLS.dis [/bc] (Chunk #34)"

#line 1 "lib/Message/DOM/DOMLS.dis [/b] (Chunk #36)"
}

#line 1 "lib/Message/DOM/DOMLS.dis [/bc] (Chunk #38)"
}}
sub certified_text ($;$) {
if (@_ == 1) {
#line 1 "lib/Message/DOM/DOMLS.dis [bc] (Chunk #45)"
my ($self) = @_;
my $r = 0;

{
#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSInput][@QName=ManakaiDOMLSInput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=certifiedText][@type=DISLang|Attribute]/Get[@Type=DOMMain:boolean||ManakaiDOM|all][@type=DISLang|AttributeGet]/PerlDef [b] (Chunk #43)"

#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSInput][@QName=ManakaiDOMLSInput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=certifiedText][@type=DISLang|Attribute]/Get[@Type=DOMMain:boolean||ManakaiDOM|all][@type=DISLang|AttributeGet]/PerlDef [bc] (Chunk #41)"

#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSInput][@QName=ManakaiDOMLSInput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=certifiedText][@type=DISLang|Attribute]/Get[@Type=DOMMain:boolean||ManakaiDOM|all][@type=DISLang|AttributeGet]/PerlDef [u] (Chunk #39)"
$r = $self->{certified_text};
#line 1 "lib/Message/DOM/DOMLS.dis [/u] (Chunk #40)"

#line 1 "lib/Message/DOM/DOMLS.dis [/bc] (Chunk #42)"

#line 1 "lib/Message/DOM/DOMLS.dis [/b] (Chunk #44)"
}
$r;

#line 1 "lib/Message/DOM/DOMLS.dis [/bc] (Chunk #46)"
} else {
#line 1 "lib/Message/DOM/DOMLS.dis [bc] (Chunk #53)"
my ($self, $given) = @_;

{
#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSInput][@QName=ManakaiDOMLSInput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=certifiedText][@type=DISLang|Attribute]/Set[@Type=DOMMain:boolean||ManakaiDOM|all][@type=DISLang|AttributeSet]/PerlDef [b] (Chunk #51)"

#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSInput][@QName=ManakaiDOMLSInput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=certifiedText][@type=DISLang|Attribute]/Set[@Type=DOMMain:boolean||ManakaiDOM|all][@type=DISLang|AttributeSet]/PerlDef [bc] (Chunk #49)"

#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSInput][@QName=ManakaiDOMLSInput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=certifiedText][@type=DISLang|Attribute]/Set[@Type=DOMMain:boolean||ManakaiDOM|all][@type=DISLang|AttributeSet]/PerlDef [u] (Chunk #47)"
$self->{certified_text} = $given;
#line 1 "lib/Message/DOM/DOMLS.dis [/u] (Chunk #48)"

#line 1 "lib/Message/DOM/DOMLS.dis [/bc] (Chunk #50)"

#line 1 "lib/Message/DOM/DOMLS.dis [/b] (Chunk #52)"
}

#line 1 "lib/Message/DOM/DOMLS.dis [/bc] (Chunk #54)"
}}
sub system_id ($;$) {
if (@_ == 1) {
#line 1 "lib/Message/DOM/DOMLS.dis [bc] (Chunk #61)"
my ($self) = @_;
my $r;

{
#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSInput][@QName=ManakaiDOMLSInput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=systemId][@Type=DOMMain:DOMString][@type=DISLang|Attribute]/Get[@type=DISLang|AttributeGet]/PerlDef [b] (Chunk #59)"

#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSInput][@QName=ManakaiDOMLSInput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=systemId][@Type=DOMMain:DOMString][@type=DISLang|Attribute]/Get[@type=DISLang|AttributeGet]/PerlDef [bc] (Chunk #57)"

#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSInput][@QName=ManakaiDOMLSInput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=systemId][@Type=DOMMain:DOMString][@type=DISLang|Attribute]/Get[@type=DISLang|AttributeGet]/PerlDef [u] (Chunk #55)"
$r = $self->{system_id};
#line 1 "lib/Message/DOM/DOMLS.dis [/u] (Chunk #56)"

#line 1 "lib/Message/DOM/DOMLS.dis [/bc] (Chunk #58)"

#line 1 "lib/Message/DOM/DOMLS.dis [/b] (Chunk #60)"
}
$r;

#line 1 "lib/Message/DOM/DOMLS.dis [/bc] (Chunk #62)"
} else {
#line 1 "lib/Message/DOM/DOMLS.dis [bc] (Chunk #69)"
my ($self, $given) = @_;

{
#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSInput][@QName=ManakaiDOMLSInput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=systemId][@Type=DOMMain:DOMString][@type=DISLang|Attribute]/Set[@type=DISLang|AttributeSet]/PerlDef [b] (Chunk #67)"

#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSInput][@QName=ManakaiDOMLSInput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=systemId][@Type=DOMMain:DOMString][@type=DISLang|Attribute]/Set[@type=DISLang|AttributeSet]/PerlDef [bc] (Chunk #65)"

#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSInput][@QName=ManakaiDOMLSInput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=systemId][@Type=DOMMain:DOMString][@type=DISLang|Attribute]/Set[@type=DISLang|AttributeSet]/PerlDef [u] (Chunk #63)"
$self->{system_id} = $given;
#line 1 "lib/Message/DOM/DOMLS.dis [/u] (Chunk #64)"

#line 1 "lib/Message/DOM/DOMLS.dis [/bc] (Chunk #66)"

#line 1 "lib/Message/DOM/DOMLS.dis [/b] (Chunk #68)"
}

#line 1 "lib/Message/DOM/DOMLS.dis [/bc] (Chunk #70)"
}}
sub string_data ($;$) {
if (@_ == 1) {
#line 1 "lib/Message/DOM/DOMLS.dis [bc] (Chunk #77)"
my ($self) = @_;
my $r;

{
#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSInput][@QName=ManakaiDOMLSInput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=stringData][@Type=DOMMain:DOMString][@type=DISLang|Attribute]/Get[@type=DISLang|AttributeGet]/PerlDef [b] (Chunk #75)"

#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSInput][@QName=ManakaiDOMLSInput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=stringData][@Type=DOMMain:DOMString][@type=DISLang|Attribute]/Get[@type=DISLang|AttributeGet]/PerlDef [bc] (Chunk #73)"

#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSInput][@QName=ManakaiDOMLSInput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=stringData][@Type=DOMMain:DOMString][@type=DISLang|Attribute]/Get[@type=DISLang|AttributeGet]/PerlDef [u] (Chunk #71)"
$r = ref $self->{string_data} eq 'SCALAR'
       ? ${$self->{string_data}} : $self->{string_data};
#line 1 "lib/Message/DOM/DOMLS.dis [/u] (Chunk #72)"

#line 1 "lib/Message/DOM/DOMLS.dis [/bc] (Chunk #74)"

#line 1 "lib/Message/DOM/DOMLS.dis [/b] (Chunk #76)"
}
$r;

#line 1 "lib/Message/DOM/DOMLS.dis [/bc] (Chunk #78)"
} else {
#line 1 "lib/Message/DOM/DOMLS.dis [bc] (Chunk #85)"
my ($self, $given) = @_;

{
#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSInput][@QName=ManakaiDOMLSInput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=stringData][@Type=DOMMain:DOMString][@type=DISLang|Attribute]/Set[@type=DISLang|AttributeSet]/PerlDef [b] (Chunk #83)"

#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSInput][@QName=ManakaiDOMLSInput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=stringData][@Type=DOMMain:DOMString][@type=DISLang|Attribute]/Set[@type=DISLang|AttributeSet]/PerlDef [bc] (Chunk #81)"

#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSInput][@QName=ManakaiDOMLSInput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=stringData][@Type=DOMMain:DOMString][@type=DISLang|Attribute]/Set[@type=DISLang|AttributeSet]/PerlDef [u] (Chunk #79)"
$self->{string_data} = ref $given eq 'SCALAR' ? $given : \$given;
#line 1 "lib/Message/DOM/DOMLS.dis [/u] (Chunk #80)"

#line 1 "lib/Message/DOM/DOMLS.dis [/bc] (Chunk #82)"

#line 1 "lib/Message/DOM/DOMLS.dis [/b] (Chunk #84)"
}

#line 1 "lib/Message/DOM/DOMLS.dis [/bc] (Chunk #86)"
}}
sub character_stream ($;$) {
if (@_ == 1) {
#line 1 "lib/Message/DOM/DOMLS.dis [bc] (Chunk #93)"
my ($self) = @_;
my $r;

{
#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSInput][@QName=ManakaiDOMLSInput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=characterStream][@type=DISLang|Attribute]/Get[@Type=LSReader][@type=DISLang|AttributeGet]/PerlDef [b] (Chunk #91)"

#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSInput][@QName=ManakaiDOMLSInput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=characterStream][@type=DISLang|Attribute]/Get[@Type=LSReader][@type=DISLang|AttributeGet]/PerlDef [bc] (Chunk #89)"

#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSInput][@QName=ManakaiDOMLSInput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=characterStream][@type=DISLang|Attribute]/Get[@Type=LSReader][@type=DISLang|AttributeGet]/PerlDef [u] (Chunk #87)"
$r = $self->{character_stream};
#line 1 "lib/Message/DOM/DOMLS.dis [/u] (Chunk #88)"

#line 1 "lib/Message/DOM/DOMLS.dis [/bc] (Chunk #90)"

#line 1 "lib/Message/DOM/DOMLS.dis [/b] (Chunk #92)"
}
$r;

#line 1 "lib/Message/DOM/DOMLS.dis [/bc] (Chunk #94)"
} else {
#line 1 "lib/Message/DOM/DOMLS.dis [bc] (Chunk #101)"
my ($self, $given) = @_;

{
#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSInput][@QName=ManakaiDOMLSInput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=characterStream][@type=DISLang|Attribute]/Set[@Type=LSReader][@type=DISLang|AttributeSet]/PerlDef [b] (Chunk #99)"

#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSInput][@QName=ManakaiDOMLSInput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=characterStream][@type=DISLang|Attribute]/Set[@Type=LSReader][@type=DISLang|AttributeSet]/PerlDef [bc] (Chunk #97)"

#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSInput][@QName=ManakaiDOMLSInput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=characterStream][@type=DISLang|Attribute]/Set[@Type=LSReader][@type=DISLang|AttributeSet]/PerlDef [u] (Chunk #95)"
$self->{character_stream} = $given;
#line 1 "lib/Message/DOM/DOMLS.dis [/u] (Chunk #96)"

#line 1 "lib/Message/DOM/DOMLS.dis [/bc] (Chunk #98)"

#line 1 "lib/Message/DOM/DOMLS.dis [/b] (Chunk #100)"
}

#line 1 "lib/Message/DOM/DOMLS.dis [/bc] (Chunk #102)"
}}
sub _new ($) {
my ($self) = @_;
my $r;

{
#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSInput][@QName=ManakaiDOMLSInput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/IntMethod[@Name=new][@type=DISLang|Method]/Return[@Type=ManakaiDOMLSInput][@type=DISLang|MethodReturn]/PerlDef [b] (Chunk #107)"

#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSInput][@QName=ManakaiDOMLSInput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/IntMethod[@Name=new][@type=DISLang|Method]/Return[@Type=ManakaiDOMLSInput][@type=DISLang|MethodReturn]/PerlDef [bc] (Chunk #105)"

#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSInput][@QName=ManakaiDOMLSInput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/IntMethod[@Name=new][@type=DISLang|Method]/Return[@Type=ManakaiDOMLSInput][@type=DISLang|MethodReturn]/PerlDef [u] (Chunk #103)"
$r = bless {}, $self;
#line 1 "lib/Message/DOM/DOMLS.dis [/u] (Chunk #104)"

#line 1 "lib/Message/DOM/DOMLS.dis [/bc] (Chunk #106)"

#line 1 "lib/Message/DOM/DOMLS.dis [/b] (Chunk #108)"
}
$r}
sub base_uri ($;$) {
if (@_ == 1) {
#line 1 "lib/Message/DOM/DOMLS.dis [bc] (Chunk #115)"
my ($self) = @_;
my $r;

{
#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSInput][@QName=ManakaiDOMLSInput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=baseURI][@Type=DOMMain:DOMString][@type=DISLang|Attribute]/Get[@type=DISLang|AttributeGet]/PerlDef [b] (Chunk #113)"

#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSInput][@QName=ManakaiDOMLSInput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=baseURI][@Type=DOMMain:DOMString][@type=DISLang|Attribute]/Get[@type=DISLang|AttributeGet]/PerlDef [bc] (Chunk #111)"

#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSInput][@QName=ManakaiDOMLSInput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=baseURI][@Type=DOMMain:DOMString][@type=DISLang|Attribute]/Get[@type=DISLang|AttributeGet]/PerlDef [u] (Chunk #109)"
$r = $self->{base_uri};
#line 1 "lib/Message/DOM/DOMLS.dis [/u] (Chunk #110)"

#line 1 "lib/Message/DOM/DOMLS.dis [/bc] (Chunk #112)"

#line 1 "lib/Message/DOM/DOMLS.dis [/b] (Chunk #114)"
}
$r;

#line 1 "lib/Message/DOM/DOMLS.dis [/bc] (Chunk #116)"
} else {
#line 1 "lib/Message/DOM/DOMLS.dis [bc] (Chunk #133)"
my ($self, $given) = @_;

{
#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSInput][@QName=ManakaiDOMLSInput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=baseURI][@Type=DOMMain:DOMString][@type=DISLang|Attribute]/Set[@type=DISLang|AttributeSet]/PerlDef [b] (Chunk #131)"

#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSInput][@QName=ManakaiDOMLSInput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=baseURI][@Type=DOMMain:DOMString][@type=DISLang|Attribute]/Set[@type=DISLang|AttributeSet]/PerlDef [bc] (Chunk #119)"
if 
#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSInput][@QName=ManakaiDOMLSInput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=baseURI][@Type=DOMMain:DOMString][@type=DISLang|Attribute]/Set[@type=DISLang|AttributeSet]/PerlDef [u] (Chunk #117)"
(not defined $given) {
  
#line 1 "lib/Message/DOM/DOMLS.dis [/u] (Chunk #118)"

#line 1 "lib/Message/DOM/DOMLS.dis [/bc] (Chunk #120)"
report Message::DOM::DOMMain::ManakaiDOMImplementationWarning -object => $self, '-type' => 'BAD_BASE_URI', 'http://suika.fam.cx/~wakaba/archive/2004/8/4/manakai-dom-exception#on' => 'set', 'http://suika.fam.cx/~wakaba/archive/2004/8/4/manakai-dom-exception#subtype' => 'http://suika.fam.cx/~wakaba/archive/2004/8/4/manakai-dom-exception#NULL_BASE_URI', 'http://suika.fam.cx/~wakaba/archive/2004/8/4/manakai-dom-exception#class' => 'Message::DOM::DOMLS::ManakaiDOMLSInput', 'http://suika.fam.cx/~wakaba/archive/2004/8/4/manakai-dom-exception#attr' => 'base_uri';

#line 4 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSInput][@QName=ManakaiDOMLSInput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=baseURI][@Type=DOMMain:DOMString][@type=DISLang|Attribute]/Set[@type=DISLang|AttributeSet]/PerlDef [bc] (Chunk #125)"

#line 4 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSInput][@QName=ManakaiDOMLSInput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=baseURI][@Type=DOMMain:DOMString][@type=DISLang|Attribute]/Set[@type=DISLang|AttributeSet]/PerlDef [u] (Chunk #121)"
;
} elsif (
#line 1 "lib/Message/DOM/DOMLS.dis [/u] (Chunk #122)"
($given !~ /\A[0-9A-Za-z+_.%-]+:/)
#line 5 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSInput][@QName=ManakaiDOMLSInput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=baseURI][@Type=DOMMain:DOMString][@type=DISLang|Attribute]/Set[@type=DISLang|AttributeSet]/PerlDef [u] (Chunk #123)"
) {
  
#line 1 "lib/Message/DOM/DOMLS.dis [/u] (Chunk #124)"

#line 1 "lib/Message/DOM/DOMLS.dis [/bc] (Chunk #126)"
report Message::DOM::DOMMain::ManakaiDOMImplementationWarning -object => $self, '-type' => 'BAD_BASE_URI', 'http://www.w3.org/2001/04/infoset#baseURI' => $given, 'http://suika.fam.cx/~wakaba/archive/2004/8/4/manakai-dom-exception#on' => 'set', 'http://suika.fam.cx/~wakaba/archive/2004/8/4/manakai-dom-exception#subtype' => 'http://suika.fam.cx/~wakaba/archive/2004/8/4/manakai-dom-exception#RELATIVE_BASE_URI', 'http://suika.fam.cx/~wakaba/archive/2004/8/4/manakai-dom-exception#class' => 'Message::DOM::DOMLS::ManakaiDOMLSInput', 'http://suika.fam.cx/~wakaba/archive/2004/8/4/manakai-dom-exception#attr' => 'base_uri';

#line 9 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSInput][@QName=ManakaiDOMLSInput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=baseURI][@Type=DOMMain:DOMString][@type=DISLang|Attribute]/Set[@type=DISLang|AttributeSet]/PerlDef [bc] (Chunk #129)"

#line 9 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSInput][@QName=ManakaiDOMLSInput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=baseURI][@Type=DOMMain:DOMString][@type=DISLang|Attribute]/Set[@type=DISLang|AttributeSet]/PerlDef [u] (Chunk #127)"
;
}
$self->{base_uri} = $given;
#line 1 "lib/Message/DOM/DOMLS.dis [/u] (Chunk #128)"

#line 1 "lib/Message/DOM/DOMLS.dis [/bc] (Chunk #130)"

#line 1 "lib/Message/DOM/DOMLS.dis [/b] (Chunk #132)"
}

#line 1 "lib/Message/DOM/DOMLS.dis [/bc] (Chunk #134)"
}}
sub encoding ($;$) {
if (@_ == 1) {
#line 1 "lib/Message/DOM/DOMLS.dis [bc] (Chunk #141)"
my ($self) = @_;
my $r;

{
#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSInput][@QName=ManakaiDOMLSInput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=encoding][@Type=DOMMain:DOMString][@type=DISLang|Attribute]/Get[@type=DISLang|AttributeGet]/PerlDef [b] (Chunk #139)"

#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSInput][@QName=ManakaiDOMLSInput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=encoding][@Type=DOMMain:DOMString][@type=DISLang|Attribute]/Get[@type=DISLang|AttributeGet]/PerlDef [bc] (Chunk #137)"

#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSInput][@QName=ManakaiDOMLSInput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=encoding][@Type=DOMMain:DOMString][@type=DISLang|Attribute]/Get[@type=DISLang|AttributeGet]/PerlDef [u] (Chunk #135)"
$r = $self->{encoding};
#line 1 "lib/Message/DOM/DOMLS.dis [/u] (Chunk #136)"

#line 1 "lib/Message/DOM/DOMLS.dis [/bc] (Chunk #138)"

#line 1 "lib/Message/DOM/DOMLS.dis [/b] (Chunk #140)"
}
$r;

#line 1 "lib/Message/DOM/DOMLS.dis [/bc] (Chunk #142)"
} else {
#line 1 "lib/Message/DOM/DOMLS.dis [bc] (Chunk #149)"
my ($self, $given) = @_;

{
#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSInput][@QName=ManakaiDOMLSInput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=encoding][@Type=DOMMain:DOMString][@type=DISLang|Attribute]/Set[@type=DISLang|AttributeSet]/PerlDef [b] (Chunk #147)"

#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSInput][@QName=ManakaiDOMLSInput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=encoding][@Type=DOMMain:DOMString][@type=DISLang|Attribute]/Set[@type=DISLang|AttributeSet]/PerlDef [bc] (Chunk #145)"

#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSInput][@QName=ManakaiDOMLSInput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=encoding][@Type=DOMMain:DOMString][@type=DISLang|Attribute]/Set[@type=DISLang|AttributeSet]/PerlDef [u] (Chunk #143)"
$self->{encoding} = $given;
#line 1 "lib/Message/DOM/DOMLS.dis [/u] (Chunk #144)"

#line 1 "lib/Message/DOM/DOMLS.dis [/bc] (Chunk #146)"

#line 1 "lib/Message/DOM/DOMLS.dis [/b] (Chunk #148)"
}

#line 1 "lib/Message/DOM/DOMLS.dis [/bc] (Chunk #150)"
}}
sub byte_stream ($;$) {
if (@_ == 1) {
#line 1 "lib/Message/DOM/DOMLS.dis [bc] (Chunk #157)"
my ($self) = @_;
my $r;

{
#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSInput][@QName=ManakaiDOMLSInput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=byteStream][@type=DISLang|Attribute]/Get[@Type=LSInputStream][@type=DISLang|AttributeGet]/PerlDef [b] (Chunk #155)"

#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSInput][@QName=ManakaiDOMLSInput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=byteStream][@type=DISLang|Attribute]/Get[@Type=LSInputStream][@type=DISLang|AttributeGet]/PerlDef [bc] (Chunk #153)"

#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSInput][@QName=ManakaiDOMLSInput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=byteStream][@type=DISLang|Attribute]/Get[@Type=LSInputStream][@type=DISLang|AttributeGet]/PerlDef [u] (Chunk #151)"
$r = $self->{byte_stream};
#line 1 "lib/Message/DOM/DOMLS.dis [/u] (Chunk #152)"

#line 1 "lib/Message/DOM/DOMLS.dis [/bc] (Chunk #154)"

#line 1 "lib/Message/DOM/DOMLS.dis [/b] (Chunk #156)"
}
$r;

#line 1 "lib/Message/DOM/DOMLS.dis [/bc] (Chunk #158)"
} else {
#line 1 "lib/Message/DOM/DOMLS.dis [bc] (Chunk #165)"
my ($self, $given) = @_;

{
#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSInput][@QName=ManakaiDOMLSInput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=byteStream][@type=DISLang|Attribute]/Set[@Type=LSInputStream][@type=DISLang|AttributeSet]/PerlDef [b] (Chunk #163)"

#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSInput][@QName=ManakaiDOMLSInput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=byteStream][@type=DISLang|Attribute]/Set[@Type=LSInputStream][@type=DISLang|AttributeSet]/PerlDef [bc] (Chunk #161)"

#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSInput][@QName=ManakaiDOMLSInput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=byteStream][@type=DISLang|Attribute]/Set[@Type=LSInputStream][@type=DISLang|AttributeSet]/PerlDef [u] (Chunk #159)"
$self->{byte_stream} = $given;
#line 1 "lib/Message/DOM/DOMLS.dis [/u] (Chunk #160)"

#line 1 "lib/Message/DOM/DOMLS.dis [/bc] (Chunk #162)"

#line 1 "lib/Message/DOM/DOMLS.dis [/b] (Chunk #164)"
}

#line 1 "lib/Message/DOM/DOMLS.dis [/bc] (Chunk #166)"
}}
$Message::DOM::ClassFeature{q<Message::DOM::DOMLS::ManakaiDOMLSInput>} = {'ls-async', {'', '1', '3.0', '1'}, 'ls', {'', '1', '3.0', '1'}};
$Message::DOM::ClassPoint{q<Message::DOM::DOMLS::ManakaiDOMLSInput>} = 6;
package Message::DOM::DOMLS::ManakaiDOMLSOutput;
our $VERSION = 20050928.0355;
push our @ISA, 'Message::DOM::DOMMain::ManakaiDOMObject', 'Message::DOM::IF::LSOutput', 'Message::DOM::IFLatest::LSOutput', 'Message::DOM::IFLevel3::LSOutput';
sub system_id ($;$) {
if (@_ == 1) {
#line 1 "lib/Message/DOM/DOMLS.dis [bc] (Chunk #173)"
my ($self) = @_;
my $r;

{
#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSOutput][@QName=ManakaiDOMLSOutput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=systemId][@Type=DOMMain:DOMString][@type=DISLang|Attribute]/Get[@type=DISLang|AttributeGet]/PerlDef [b] (Chunk #171)"

#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSOutput][@QName=ManakaiDOMLSOutput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=systemId][@Type=DOMMain:DOMString][@type=DISLang|Attribute]/Get[@type=DISLang|AttributeGet]/PerlDef [bc] (Chunk #169)"

#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSOutput][@QName=ManakaiDOMLSOutput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=systemId][@Type=DOMMain:DOMString][@type=DISLang|Attribute]/Get[@type=DISLang|AttributeGet]/PerlDef [u] (Chunk #167)"
$r = $self->{systemId};
#line 1 "lib/Message/DOM/DOMLS.dis [/u] (Chunk #168)"

#line 1 "lib/Message/DOM/DOMLS.dis [/bc] (Chunk #170)"

#line 1 "lib/Message/DOM/DOMLS.dis [/b] (Chunk #172)"
}
$r;

#line 1 "lib/Message/DOM/DOMLS.dis [/bc] (Chunk #174)"
} else {
#line 1 "lib/Message/DOM/DOMLS.dis [bc] (Chunk #187)"
my ($self, $given) = @_;

{
#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSOutput][@QName=ManakaiDOMLSOutput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=systemId][@Type=DOMMain:DOMString][@type=DISLang|Attribute]/Set[@type=DISLang|AttributeSet]/PerlDef [b] (Chunk #185)"

#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSOutput][@QName=ManakaiDOMLSOutput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=systemId][@Type=DOMMain:DOMString][@type=DISLang|Attribute]/Set[@type=DISLang|AttributeSet]/PerlDef [bc] (Chunk #179)"
if 
#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSOutput][@QName=ManakaiDOMLSOutput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=systemId][@Type=DOMMain:DOMString][@type=DISLang|Attribute]/Set[@type=DISLang|AttributeSet]/PerlDef [u] (Chunk #175)"
(
#line 1 "lib/Message/DOM/DOMLS.dis [/u] (Chunk #176)"
($given !~ /\A[0-9A-Za-z+_.%-]+:/)
#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSOutput][@QName=ManakaiDOMLSOutput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=systemId][@Type=DOMMain:DOMString][@type=DISLang|Attribute]/Set[@type=DISLang|AttributeSet]/PerlDef [u] (Chunk #177)"
) {
  
#line 1 "lib/Message/DOM/DOMLS.dis [/u] (Chunk #178)"

#line 1 "lib/Message/DOM/DOMLS.dis [/bc] (Chunk #180)"
report Message::DOM::DOMMain::ManakaiDOMImplementationWarning -object => $self, '-type' => 'RELATIVE_URI', 'http://suika.fam.cx/~wakaba/archive/2004/8/4/manakai-dom-exception#on' => 'set', 'http://suika.fam.cx/~wakaba/archive/2004/8/4/manakai-dom-exception#class' => 'Message::DOM::DOMLS::ManakaiDOMLSOutput', 'http://suika.fam.cx/~wakaba/archive/2004/8/4/manakai-dom-exception#attr' => 'system_id', 'http://suika.fam.cx/~wakaba/archive/2004/8/4/manakai-dom-exception#uri' => $given;

#line 5 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSOutput][@QName=ManakaiDOMLSOutput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=systemId][@Type=DOMMain:DOMString][@type=DISLang|Attribute]/Set[@type=DISLang|AttributeSet]/PerlDef [bc] (Chunk #183)"

#line 5 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSOutput][@QName=ManakaiDOMLSOutput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=systemId][@Type=DOMMain:DOMString][@type=DISLang|Attribute]/Set[@type=DISLang|AttributeSet]/PerlDef [u] (Chunk #181)"
;
}
$self->{systemId} = $given;
#line 1 "lib/Message/DOM/DOMLS.dis [/u] (Chunk #182)"

#line 1 "lib/Message/DOM/DOMLS.dis [/bc] (Chunk #184)"

#line 1 "lib/Message/DOM/DOMLS.dis [/b] (Chunk #186)"
}

#line 1 "lib/Message/DOM/DOMLS.dis [/bc] (Chunk #188)"
}}
sub character_stream ($;$) {
if (@_ == 1) {
#line 1 "lib/Message/DOM/DOMLS.dis [bc] (Chunk #195)"
my ($self) = @_;
my $r;

{
#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSOutput][@QName=ManakaiDOMLSOutput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=characterStream][@type=DISLang|Attribute]/Get[@Type=LSWriter][@type=DISLang|AttributeGet]/PerlDef [b] (Chunk #193)"

#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSOutput][@QName=ManakaiDOMLSOutput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=characterStream][@type=DISLang|Attribute]/Get[@Type=LSWriter][@type=DISLang|AttributeGet]/PerlDef [bc] (Chunk #191)"

#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSOutput][@QName=ManakaiDOMLSOutput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=characterStream][@type=DISLang|Attribute]/Get[@Type=LSWriter][@type=DISLang|AttributeGet]/PerlDef [u] (Chunk #189)"
$r = $self->{characterStream};
#line 1 "lib/Message/DOM/DOMLS.dis [/u] (Chunk #190)"

#line 1 "lib/Message/DOM/DOMLS.dis [/bc] (Chunk #192)"

#line 1 "lib/Message/DOM/DOMLS.dis [/b] (Chunk #194)"
}
$r;

#line 1 "lib/Message/DOM/DOMLS.dis [/bc] (Chunk #196)"
} else {
#line 1 "lib/Message/DOM/DOMLS.dis [bc] (Chunk #203)"
my ($self, $given) = @_;

{
#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSOutput][@QName=ManakaiDOMLSOutput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=characterStream][@type=DISLang|Attribute]/Set[@Type=LSWriter][@type=DISLang|AttributeSet]/PerlDef [b] (Chunk #201)"

#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSOutput][@QName=ManakaiDOMLSOutput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=characterStream][@type=DISLang|Attribute]/Set[@Type=LSWriter][@type=DISLang|AttributeSet]/PerlDef [bc] (Chunk #199)"

#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSOutput][@QName=ManakaiDOMLSOutput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=characterStream][@type=DISLang|Attribute]/Set[@Type=LSWriter][@type=DISLang|AttributeSet]/PerlDef [u] (Chunk #197)"
$self->{characterStream} = $given;
#line 1 "lib/Message/DOM/DOMLS.dis [/u] (Chunk #198)"

#line 1 "lib/Message/DOM/DOMLS.dis [/bc] (Chunk #200)"

#line 1 "lib/Message/DOM/DOMLS.dis [/b] (Chunk #202)"
}

#line 1 "lib/Message/DOM/DOMLS.dis [/bc] (Chunk #204)"
}}
sub _new ($) {
my ($self) = @_;
my $r;

{
#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSOutput][@QName=ManakaiDOMLSOutput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/IntMethod[@Name=new][@type=DISLang|Method]/Return[@Type=ManakaiDOMLSOutput][@type=DISLang|MethodReturn]/PerlDef [b] (Chunk #209)"

#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSOutput][@QName=ManakaiDOMLSOutput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/IntMethod[@Name=new][@type=DISLang|Method]/Return[@Type=ManakaiDOMLSOutput][@type=DISLang|MethodReturn]/PerlDef [bc] (Chunk #207)"

#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSOutput][@QName=ManakaiDOMLSOutput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/IntMethod[@Name=new][@type=DISLang|Method]/Return[@Type=ManakaiDOMLSOutput][@type=DISLang|MethodReturn]/PerlDef [u] (Chunk #205)"
$r = bless {}, $self;
#line 1 "lib/Message/DOM/DOMLS.dis [/u] (Chunk #206)"

#line 1 "lib/Message/DOM/DOMLS.dis [/bc] (Chunk #208)"

#line 1 "lib/Message/DOM/DOMLS.dis [/b] (Chunk #210)"
}
$r}
sub encoding ($;$) {
if (@_ == 1) {
#line 1 "lib/Message/DOM/DOMLS.dis [bc] (Chunk #217)"
my ($self) = @_;
my $r;

{
#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSOutput][@QName=ManakaiDOMLSOutput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=encoding][@Type=DOMMain:DOMString][@type=DISLang|Attribute]/Get[@type=DISLang|AttributeGet]/PerlDef [b] (Chunk #215)"

#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSOutput][@QName=ManakaiDOMLSOutput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=encoding][@Type=DOMMain:DOMString][@type=DISLang|Attribute]/Get[@type=DISLang|AttributeGet]/PerlDef [bc] (Chunk #213)"

#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSOutput][@QName=ManakaiDOMLSOutput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=encoding][@Type=DOMMain:DOMString][@type=DISLang|Attribute]/Get[@type=DISLang|AttributeGet]/PerlDef [u] (Chunk #211)"
$r = $self->{encoding};
#line 1 "lib/Message/DOM/DOMLS.dis [/u] (Chunk #212)"

#line 1 "lib/Message/DOM/DOMLS.dis [/bc] (Chunk #214)"

#line 1 "lib/Message/DOM/DOMLS.dis [/b] (Chunk #216)"
}
$r;

#line 1 "lib/Message/DOM/DOMLS.dis [/bc] (Chunk #218)"
} else {
#line 1 "lib/Message/DOM/DOMLS.dis [bc] (Chunk #225)"
my ($self, $given) = @_;

{
#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSOutput][@QName=ManakaiDOMLSOutput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=encoding][@Type=DOMMain:DOMString][@type=DISLang|Attribute]/Set[@type=DISLang|AttributeSet]/PerlDef [b] (Chunk #223)"

#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSOutput][@QName=ManakaiDOMLSOutput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=encoding][@Type=DOMMain:DOMString][@type=DISLang|Attribute]/Set[@type=DISLang|AttributeSet]/PerlDef [bc] (Chunk #221)"

#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSOutput][@QName=ManakaiDOMLSOutput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=encoding][@Type=DOMMain:DOMString][@type=DISLang|Attribute]/Set[@type=DISLang|AttributeSet]/PerlDef [u] (Chunk #219)"
$self->{encoding} = $given;
#line 1 "lib/Message/DOM/DOMLS.dis [/u] (Chunk #220)"

#line 1 "lib/Message/DOM/DOMLS.dis [/bc] (Chunk #222)"

#line 1 "lib/Message/DOM/DOMLS.dis [/b] (Chunk #224)"
}

#line 1 "lib/Message/DOM/DOMLS.dis [/bc] (Chunk #226)"
}}
sub byte_stream ($;$) {
if (@_ == 1) {
#line 1 "lib/Message/DOM/DOMLS.dis [bc] (Chunk #233)"
my ($self) = @_;
my $r;

{
#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSOutput][@QName=ManakaiDOMLSOutput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=byteStream][@type=DISLang|Attribute]/Get[@Type=LSOutputStream][@type=DISLang|AttributeGet]/PerlDef [b] (Chunk #231)"

#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSOutput][@QName=ManakaiDOMLSOutput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=byteStream][@type=DISLang|Attribute]/Get[@Type=LSOutputStream][@type=DISLang|AttributeGet]/PerlDef [bc] (Chunk #229)"

#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSOutput][@QName=ManakaiDOMLSOutput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=byteStream][@type=DISLang|Attribute]/Get[@Type=LSOutputStream][@type=DISLang|AttributeGet]/PerlDef [u] (Chunk #227)"
$r = $self->{byteStream};
#line 1 "lib/Message/DOM/DOMLS.dis [/u] (Chunk #228)"

#line 1 "lib/Message/DOM/DOMLS.dis [/bc] (Chunk #230)"

#line 1 "lib/Message/DOM/DOMLS.dis [/b] (Chunk #232)"
}
$r;

#line 1 "lib/Message/DOM/DOMLS.dis [/bc] (Chunk #234)"
} else {
#line 1 "lib/Message/DOM/DOMLS.dis [bc] (Chunk #241)"
my ($self, $given) = @_;

{
#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSOutput][@QName=ManakaiDOMLSOutput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=byteStream][@type=DISLang|Attribute]/Set[@Type=LSOutputStream][@type=DISLang|AttributeSet]/PerlDef [b] (Chunk #239)"

#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSOutput][@QName=ManakaiDOMLSOutput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=byteStream][@type=DISLang|Attribute]/Set[@Type=LSOutputStream][@type=DISLang|AttributeSet]/PerlDef [bc] (Chunk #237)"

#line 1 "/document (lib/Message/DOM/DOMLS.dis)/IFCls3Def[@QName=LSOutput][@QName=ManakaiDOMLSOutput][@type=dis|MultipleResource][@type=ManakaiDOM|IF][@type=ManakaiDOM|Class]/Attr[@Name=byteStream][@type=DISLang|Attribute]/Set[@Type=LSOutputStream][@type=DISLang|AttributeSet]/PerlDef [u] (Chunk #235)"
$self->{byteStream} = $given;
#line 1 "lib/Message/DOM/DOMLS.dis [/u] (Chunk #236)"

#line 1 "lib/Message/DOM/DOMLS.dis [/bc] (Chunk #238)"

#line 1 "lib/Message/DOM/DOMLS.dis [/b] (Chunk #240)"
}

#line 1 "lib/Message/DOM/DOMLS.dis [/bc] (Chunk #242)"
}}
$Message::DOM::ClassFeature{q<Message::DOM::DOMLS::ManakaiDOMLSOutput>} = {'ls', {'', '1', '3.0', '1'}};
$Message::DOM::ClassPoint{q<Message::DOM::DOMLS::ManakaiDOMLSOutput>} = 3;
for ($Message::DOM::IFLatest::DOMImplementationLS::, $Message::Util::IF::ManakaiDOMExceptionIF::, $Message::DOM::IF::DOMImplementationLS::, $Message::DOM::IFLatest::LSOutput::, $Message::DOM::IF::LSInput::, $Message::DOM::IFLevel3::LSException::, $Message::DOM::IFLevel3::DOMImplementationLS::, $Message::DOM::IFLevel3::LSOutput::, $Message::DOM::IFLevel3::LSInput::, $Message::DOM::IF::LSOutput::, $Message::DOM::IFLatest::LSInput::, $Message::DOM::IF::LSException::){}
## License: <http://suika.fam.cx/~wakaba/archive/2004/8/18/license#Perl+MPL>
1;
