#!/usr/bin/perl 
## This file is automatically generated
## 	at 2006-12-31T09:27:28+00:00,
## 	from file "../DOM/DOMMain.dis",
## 	module <http://suika.fam.cx/~wakaba/archive/2004/8/18/manakai-dom#ManakaiDOM.DOMMain>.
## Don't edit by hand!
use strict;
package Message::DOM::DOMMain;
our $VERSION = 20061231.0927;
$Message::DOM::DOMCore::ManakaiDOMError::Def{'http://suika.fam.cx/~wakaba/archive/2004/dom/main#empty-namespace-uri'} = {'description',
'An empty string is used as a namespace URI.',
'http://suika.fam.cx/~wakaba/archive/2005/manakai/Util/Error/Core/textFormatter',
'Message::Util::Error::formatter',
'sev',
'1',
't',
'http://suika.fam.cx/~wakaba/archive/2004/dom/main#empty-namespace-uri'};
$Message::DOM::DOMCore::ManakaiDOMError::Def{'http://suika.fam.cx/~wakaba/archive/2004/dom/main#empty-namespace-prefix'} = {'description',
'An empty string is used as a namespace prefix.',
'http://suika.fam.cx/~wakaba/archive/2005/manakai/Util/Error/Core/textFormatter',
'Message::Util::Error::formatter',
'sev',
'1',
't',
'http://suika.fam.cx/~wakaba/archive/2004/dom/main#empty-namespace-prefix'};
## License: <http://suika.fam.cx/~wakaba/archive/2004/8/18/license#Perl+MPL>
1;
