=head1 NAME

Message::DOM::TextTrackCue - DOM |TextTrackCue| object

=head1 DESCRIPTION

The C<Message::DOM::TextTrackCue> class implements the DOM
C<TextTrackCue> interface.

For WebVTT text track cues, there is a subclass,
L<Message::DOM::WebVTTCue>.

=head1 METHODS

The C<Message::DOM::TextTrackCue> object has following methods:

=over 4

=item $track = $cue->track

Return the associated C<TextTrack> object, if any, or C<undef>.
[HTML]

=item $line = $cue->manakai_line

Get the line number in the source file, if available, or C<-1>.
[MANAKAI]

=item $column = $cue->manakai_column

Get the column number in the source file, if available, or C<-1>.
[MANAKAI]

=item $id = $cue->id

=item $cue->id ($new_id)

Get or set the identifier of the cue. [HTML]

=item $seconds = $cue->start_time

=item $cue->start_time ($new_seconds)

Get or set the start time of the cue.  [HTML]

=item $seconds = $cue->end_time

=item $cue->end_time ($seconds)

Get or set the end time of the cue.  [HTML]

=item $bool = $cue->pause_on_exit

=item $cue->pause_on_exit ($new_bool)

Get or set the pause-on-exit flag of the cue.  [HTML]

=item $cue2 = $cue->manakai_clone_cue

Create a clone of the cue.  All attributes except for C<track> is
copied to the clone.  [MANAKAI]

=back

=head1 SEE ALSO

[HTML] HTML Standard
<http://www.whatwg.org/specs/web-apps/current-work/#texttrackcue>.

[MANAKAI] manakai DOM Extensions
<https://suika.suikawiki.org/~wakaba/wiki/sw/n/manakai%20DOM%20Extensions#anchor-56>.

[WEBVTT] WebVTT Standard <http://dev.w3.org/html5/webvtt/>.

L<Message::DOM::TextTrackCueList>.

L<Message::DOM::WebVTTCue>.

=head1 AUTHOR

Wakaba <wakaba@suikawiki.org>.

=head1 LICENSE

Copyright 2012-2013 Wakaba <wakaba@suikawiki.org>.

This program is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
